name: Publish docs, API ref and sample app

on:
  release:
    types: [ released ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Dist Catalog App
        run: |
          ./gradlew wasmJsBrowserDistribution --no-configuration-cache
          mkdir -p site/sample
          ls sample/compose-app/build/dist/wasmJs/productionExecutable
          cp -r sample/compose-app/build/dist/wasmJs/productionExecutable/* site/sample
          ls site/sample

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          single-commit: true
